### ISSUE TITLE
Succesfull compile with Swift 5, xCode 12.0.1, Big Sur (New to Github - who can set this "officially"?)

### ISSUE THREAD

**Issue by Jimw338** [macmade/GameOfLife#2]
I'm new to Github, so I don't know how to "officially" specify this for the project.  I just successfully compiled on Big Sur 20E5196f with xCode 12.0.1, after setting SWIFT_VERSION to 5, and deleting all the "red files" under "xcconfig".  (Are these supposed to be created by a custom build script?)

Oddly, I *didn't* have to add the "wildcard dot" to the Bundle Identifier to give it a unique identifier, as I've had to do with other projects downloaded from GitHub. 

(Rant to Apple..:  ..  "after setting Swift version".. with the "Swift Language Version" option that is buried in the MIDDLE of the General/Basic preferences pane.  Hint to Apple: why is this so hard to "intuitively" find this?  Given that it's probably the first thing that's likely "out of date" if someone just downloads a project off of GitHub?

Most new programmers probably fall into this category, and presumably "new programmers" is something Apple wants to encourage.  And highlights in ads at each new Apple event.  Adds that never get shown on television or anywhere else..  Preaching to the choir here?)

**Comment by macmade** [comment]
You need to clone recursively.
xcconfig is a submodule containing Xcode settings.
Stuff will obviously be broken without it.
